### ISSUE TITLE
Consider using https://www.npmjs.com/package/debug instead of the odd debug mechanism in lib/reporter.js

### ISSUE THREAD

**Issue by aucampia** [dhis2/cli-helpers-engine#26]
Currently the verbosity of `lib/reporter.js` is controlled via yargs middleware which is not really the right way to do things as it uses a mechanism which is not intended for adding command line parameters to add a command line parameter and thus it does not end up being visible in --help output. At the very least this approach should be corrected so that --verbose shows up in --help - but a better approach would be to just adopt a more standard approach for debug messages, namely https://www.npmjs.com/package/debug - which is already used by things like babel, express and eslint.

**Comment by varl** [comment]
> At the very least this approach should be corrected so that --verbose shows up in --help

Agreed, this would be nice.

> but a better approach would be to just adopt a more standard approach for debug messages

I don't agree that adopting a library modeled after how a specific team does debugging is considered a standard.

It can be widely used by convention, and even `stdin`, `stderr`, and `stdout` are technically just conventions that are widely acknowledged over decades. These are the ones that we are concerned about however, so we try to output any information that can be piped to another process to `stdout`, and any information that is generally not helpful for machine parsing to `stderr`.

Debug messages under the `--verbose` flag should be printed to `stderr` for example, if they aren't, I would probably consider that a bug.

As far as `debug` is concerned, we are discussing logging in this issue: https://github.com/dhis2/notes/issues/46. It is mostly from a webapp perspective, but there are tidbits about e.g. NodeJS and the `d2` CLI as well.
